apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: distribution-game
resources:
  - ../../base
commonLabels:
  environment: latest
commonAnnotations:
  version: 1.0.3-7e75e987--2023-06-27.1687886861 # {"$imagepolicy": "distribution-game:distribution-game-image-policy:tag"}
images:
  - name: "distribution-game"
    newName: "registry.ltc.bcit.ca/web-apps/distribution-game"
    newTag: "1.0.3-7e75e987--2023-06-27.1687886861" # {"$imagepolicy": "distribution-game:distribution-game-image-policy:tag"}
# Adds elasticapm config to deployment
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{"configMapRef": {"name":"elasticapm-config"}}]
# Generates elasticapm config
#
configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=distribution-game-latest
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
