apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: distribution-game-
nameSuffix: -latest
# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 1.0.4-af1fc0bc--2023-10-19.1697755135 # {"$imagepolicy": "distribution-game:distribution-game-image-policy-latest:tag"}
images:
  - name: "distribution-game"
    newName: "registry.ltc.bcit.ca/web-apps/distribution-game"
    newTag: "1.0.4-af1fc0bc--2023-10-19.1697755135" # {"$imagepolicy": "distribution-game:distribution-game-image-policy-latest:tag"}
# Adds elasticapm config to deployment
#
patches:
  # Patches ingress with "latest--"
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  # Adds secrets to deployment
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=distribution-game-latest
    behavior: merge
