apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=distribution-game}

resources:
- ../../base

commonLabels:
  environment: review

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
- name: distribution-game
  newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/distribution-game}
  newTag: ${IMAGE_TAG:=stable}

patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
