apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: stable
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: distribution-game-
nameSuffix: -stable
# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 1.0.3 # {"$imagepolicy": "distribution-game:distribution-game-image-policy:tag"}
  tag: ${GIT_TAG:=stable}
images:
  - name: "distribution-game"
    newName: "registry.ltc.bcit.ca/web-apps/distribution-game"
    newTag: "1.0.3" # {"$imagepolicy": "distribution-game:distribution-game-image-policy:tag"}
