apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: distribution-game

resources:
  - ../../base

commonLabels:
  environment: stable

commonAnnotations:
  version: stable # {"$imagepolicy": "flux-system:distribution-game:tag"}
  tag: ${GIT_TAG:=stable}

configMapGenerator:
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=distribution-game-stable
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{"configMapRef": {"name":"elasticapm-config"}}]

images:
  - name: "distribution-game"
    newName: "registry.ltc.bcit.ca/web-apps/distribution-game"
    newTag: "stable" # {"$imagepolicy": "flux-system:distribution-game:tag"}
