apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - ./nginx-unprivileged
  - ingress.yaml

# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml

commonLabels:
  app: distribution-game
  app.kubernetes.io/name: distribution-game

# Patch nginx base; simplify deployment name
#
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: distribution-game
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: distribution-game
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: distribution-game-serviceaccount
      - op: replace
        path: /metadata/name
        value: deployment
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value: [{"configMapRef": {"name":"elasticapm-config"}}]

configMapGenerator:
  # Generates elasticapm initial config
  #
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVER_URL=https://bcit-ltc.apm.westus2.azure.elastic-cloud.com
